// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5tDcteZURxLyNYMZOTiGqX5l2GG5SUZk',
    appId: '1:379179291742:web:c1607f5d721eb3835310cf',
    messagingSenderId: '379179291742',
    projectId: 'swift-spend',
    authDomain: 'swift-spend.firebaseapp.com',
    storageBucket: 'swift-spend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkF2R3SHTwsseDy3Nap9clBP7-RdhsybA',
    appId: '1:379179291742:android:18561419c557a3475310cf',
    messagingSenderId: '379179291742',
    projectId: 'swift-spend',
    storageBucket: 'swift-spend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy0aiW0MSx-0-dZXGx1a3sfxyb5maKbOE',
    appId: '1:379179291742:ios:a952b5c60bade6a95310cf',
    messagingSenderId: '379179291742',
    projectId: 'swift-spend',
    storageBucket: 'swift-spend.appspot.com',
    iosBundleId: 'com.wtm.savings.swiftSpend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy0aiW0MSx-0-dZXGx1a3sfxyb5maKbOE',
    appId: '1:379179291742:ios:10c1eedbb8e4d5145310cf',
    messagingSenderId: '379179291742',
    projectId: 'swift-spend',
    storageBucket: 'swift-spend.appspot.com',
    iosBundleId: 'com.wtm.savings.swiftSpend.RunnerTests',
  );
}
